"""
Synthetic safety inspection report generator.

Reuses the exact facility_id / facility_type / facility_name / city pool from
facility_risk_assessments.csv (generated by generate_risk_assessments.py) —
inspections are NOT a separate fabricated facility list. This is what lets
the two datasets join coherently later (e.g. "facilities with the worst
inspection histories also carry the highest computed_risk_score").

Each facility's latest risk assessment row is treated as its "current" risk
profile. A 10-item safety checklist is generated per inspection; each item
belongs to one of three categories, and its fail probability is driven by
the relevant normalized risk factor from that facility's risk profile:

  - surveillance-related items  -> driven by surveillance_gap_risk
    (1 - surveillance_coverage_pct / 100)
  - structural/maintenance items -> driven by vulnerability_risk
    (structural_vulnerabilities / cap)
  - staffing/procedural items    -> driven by staffing_gap_risk
    (1 - staffing_level / cap)

So a facility with low surveillance_coverage_pct in the risk dataset will
show elevated failure rates specifically on surveillance-category checklist
items here, and likewise high structural_vulnerabilities -> more structural
failures — the correlation the joint story depends on.
"""
import numpy as np
import pandas as pd

pd.set_option("display.width", 120)
pd.set_option("display.max_columns", None)

SEED = 43  # different from the risk-assessment seed so this is an independent draw
N_INSPECTIONS = 300
RISK_ASSESSMENTS_PATH = "data/synthetic/facility_risk_assessments.csv"
OUTPUT_PATH = "data/synthetic/safety_inspection_reports.csv"

NORM_CAPS = {"staffing_level": 10, "structural_vulnerabilities": 8}

INSPECTORS = [f"INSP-{n:02d}" for n in range(1, 13)]

# (item_key, category, human-readable label, base fail probability)
# Base rates reflect that some checks fail more often even at well-run
# facilities (e.g. signage drifting out of date) than others (e.g. a fire
# alarm test, which is rarely skipped regardless of facility risk profile).
CHECKLIST_ITEMS = [
    ("fire_extinguishers_current", "structural", "Fire extinguishers inspected and current", 0.035),
    ("emergency_exits_clear", "structural", "Emergency exits unobstructed and functional", 0.025),
    ("fire_alarm_tested", "structural", "Fire alarm system tested per schedule", 0.025),
    ("sprinkler_system_serviced", "structural", "Sprinkler/suppression system serviced", 0.03),
    ("structural_condition", "structural", "No unaddressed structural damage observed", 0.03),
    ("perimeter_cameras_operational", "surveillance", "Perimeter cameras operational", 0.045),
    ("access_control_functioning", "surveillance", "Access control system functioning", 0.04),
    ("security_lighting_adequate", "surveillance", "Security lighting adequate at entry points", 0.035),
    ("evacuation_plan_posted", "staffing", "Evacuation plan posted and current", 0.03),
    ("safety_signage_current", "staffing", "Safety signage current and visible", 0.03),
]

# How much a facility's normalized risk factor (0-1) can add to an item's
# base fail probability, by category. E.g. a facility at surveillance_gap_risk
# = 1.0 (0% coverage) adds up to +0.4 to every surveillance-category item.
# Kept well below 1.0 even at worst-case risk so failure isn't deterministic —
# a poorly-surveilled facility fails surveillance checks more OFTEN, not always.
CATEGORY_SENSITIVITY = {
    "structural": 0.40,
    "surveillance": 0.40,
    "staffing": 0.30,
}
FAIL_PROB_BOUNDS = (0.02, 0.90)

OVERALL_RESULT_BINS = [(0, "Pass"), (2, "Pass with Corrective Actions"), (999, "Fail")]

NOTE_TEMPLATES_CLEAN = [
    "No deficiencies noted during this inspection. Facility maintains satisfactory compliance across all checked categories.",
    "All checklist items passed. No corrective action required at this time.",
    "Facility presented in good order; inspector observed no outstanding safety concerns.",
]


def latest_risk_profile(risk_df: pd.DataFrame) -> pd.DataFrame:
    """One row per facility_id: identity fields + its most recent assessment's
    raw risk factors, used to drive this facility's inspection fail rates."""
    df = risk_df.copy()
    df["assessment_date"] = pd.to_datetime(df["assessment_date"])
    latest = df.sort_values("assessment_date").groupby("facility_id", as_index=False).last()
    return latest[[
        "facility_id", "facility_name", "facility_type", "city",
        "surveillance_coverage_pct", "staffing_level", "structural_vulnerabilities",
        "computed_risk_score",
    ]]


def generate(n_inspections: int, seed: int, risk_df: pd.DataFrame) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    profiles = latest_risk_profile(risk_df)
    facility_ids = profiles["facility_id"].to_numpy()

    rows = []
    for i in range(n_inspections):
        facility_id = rng.choice(facility_ids)
        profile = profiles.loc[profiles["facility_id"] == facility_id].iloc[0]

        surveillance_gap_risk = 1 - (profile["surveillance_coverage_pct"] / 100)
        staffing_gap_risk = 1 - (min(profile["staffing_level"], NORM_CAPS["staffing_level"]) / NORM_CAPS["staffing_level"])
        vulnerability_risk = min(profile["structural_vulnerabilities"], NORM_CAPS["structural_vulnerabilities"]) / NORM_CAPS["structural_vulnerabilities"]

        risk_by_category = {
            "surveillance": surveillance_gap_risk,
            "structural": vulnerability_risk,
            "staffing": staffing_gap_risk,
        }

        item_results = {}
        failed_labels = []
        for item_key, category, label, base_fail in CHECKLIST_ITEMS:
            p_fail = base_fail + CATEGORY_SENSITIVITY[category] * risk_by_category[category]
            p_fail = float(np.clip(p_fail, *FAIL_PROB_BOUNDS))
            passed = rng.random() > p_fail
            item_results[item_key] = "Pass" if passed else "Fail"
            if not passed:
                failed_labels.append(label)

        items_failed = len(failed_labels)
        items_checked = len(CHECKLIST_ITEMS)
        items_passed = items_checked - items_failed

        overall_result = next(label for threshold, label in OVERALL_RESULT_BINS if items_failed <= threshold)

        inspection_date = pd.Timestamp("2024-01-01") + pd.Timedelta(days=int(rng.integers(0, 730)))

        if items_failed == 0:
            notes = rng.choice(NOTE_TEMPLATES_CLEAN)
        else:
            notes = (
                f"Inspection identified {items_failed} deficiency(ies): "
                + "; ".join(failed_labels)
                + ". Recommend corrective action and re-inspection within 30 days."
            )

        row = {
            "inspection_id": f"INS-{i + 1:05d}",
            "facility_id": profile["facility_id"],
            "facility_name": profile["facility_name"],
            "facility_type": profile["facility_type"],
            "city": profile["city"],
            "inspection_date": inspection_date.date().isoformat(),
            "inspector_id": rng.choice(INSPECTORS),
        }
        row.update(item_results)
        row.update({
            "checklist_items_checked": items_checked,
            "checklist_items_passed": items_passed,
            "checklist_items_failed": items_failed,
            "overall_result": overall_result,
            "inspector_notes": notes,
        })
        rows.append(row)

    return pd.DataFrame(rows)


def main():
    risk_df = pd.read_csv(RISK_ASSESSMENTS_PATH)
    df = generate(N_INSPECTIONS, SEED, risk_df)
    df.to_csv(OUTPUT_PATH, index=False)

    print(f"Wrote {len(df)} rows to {OUTPUT_PATH}\n")
    print("Sample rows:")
    print(df.head(8).to_string(index=False))

    print("\nOverall result distribution:")
    print(df["overall_result"].value_counts())

    print("\nChecklist items failed, by facility type:")
    print(df.groupby("facility_type")["checklist_items_failed"].agg(["mean", "std", "count"]).round(2))

    # Join back to the risk assessments' latest profile to verify the
    # requested correlation actually shows up in the generated data.
    profiles = latest_risk_profile(risk_df)
    joined = df.merge(profiles, on="facility_id", suffixes=("", "_risk"))
    print("\nCorrelation check vs. underlying risk factors (expect negative for")
    print("surveillance_coverage_pct, positive for structural_vulnerabilities):")
    check_cols = [
        "surveillance_coverage_pct", "structural_vulnerabilities", "staffing_level",
        "computed_risk_score", "checklist_items_failed",
    ]
    print(joined[check_cols].corr().round(2)["checklist_items_failed"])


if __name__ == "__main__":
    main()
